# Generated by Django 5.0.2 on 2024-03-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.profile')),
            ],
            options={
                'verbose_name': 'Frind',
                'verbose_name_plural': 'Frinds',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='frinds',
            field=models.ManyToManyField(related_name='frinds', to='chat.frind'),
        ),
    ]
